### ISSUE TITLE
Wrong height for view

### ISSUE THREAD

**Issue by emans** [dbeattie71/SnackbarSharp#3]
I. Congratz for your work with this Snackbar.
I noticed a bug on Snackbar.cs. The MaxHeight attribute is getting the GetMinHeight instead of GetMaxHeight(). this causes, in my case, the view to always show only on line.

FrameLayout.LayoutParams layoutParams = null;
            if (res.GetBoolean(Resource.Boolean.sb__is_phone))
            {
                layout.SetMinimumHeight(DpToPx(_type.GetMinHeight(), scale));
                layout.SetMaxHeight(DpToPx(_type.GetMinHeight(), scale));
                layout.SetBackgroundColor(_color);
                layoutParams = new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MatchParent,
                    ViewGroup.LayoutParams.WrapContent);
            }

should be

FrameLayout.LayoutParams layoutParams = null;
            if (res.GetBoolean(Resource.Boolean.sb__is_phone))
            {
                layout.SetMinimumHeight(DpToPx(_type.GetMinHeight(), scale));
                layout.SetMaxHeight(DpToPx(_type.GetMaxHeight(), scale));
                layout.SetBackgroundColor(_color);
                layoutParams = new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MatchParent,
                    ViewGroup.LayoutParams.WrapContent);
            }

Thanks.

**Comment by dbeattie71** [comment]
Thanks, fixed and pushed to nuget.
